"""empty message

Revision ID: 07a99d211173
Revises: f7cdd29c0d08
Create Date: 2019-10-24 15:37:00.935385

"""

# revision identifiers, used by Alembic.
revision = '07a99d211173'
down_revision = 'f7cdd29c0d08'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_survey_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('lead_surveyor', sa.String(length=50), nullable=True),
    sa.Column('assistant_surveyor', sa.String(length=50), nullable=True),
    sa.Column('survey_date', sa.Date(), nullable=True),
    sa.Column('camera_kit_number', sa.String(length=25), nullable=True),
    sa.Column('external_temperature', sa.Float(), nullable=True),
    sa.Column('faults_identified', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_survey_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('householders_name', sa.String(length=50), nullable=True),
    sa.Column('address_line', sa.String(length=100), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('special_considerations', sa.Text(), nullable=True),
    sa.Column('num_main_rooms', sa.Integer(), nullable=True),
    sa.Column('can_heat_comfortably', sa.Boolean(), nullable=True),
    sa.Column('expected_benefit', sa.Text(), nullable=True),
    sa.Column('year_of_construction', sa.Integer(), nullable=True),
    sa.Column('building_type_id', sa.Integer(), nullable=True),
    sa.Column('wall_construction_type_id', sa.Integer(), nullable=True),
    sa.Column('occupation_type_id', sa.Integer(), nullable=True),
    sa.Column('primary_heating_type_id', sa.Integer(), nullable=True),
    sa.Column('secondary_heating_type_id', sa.Integer(), nullable=True),
    sa.Column('water_heating_type_id', sa.Integer(), nullable=True),
    sa.Column('cooking_type_id', sa.Integer(), nullable=True),
    sa.Column('depth_loft_insulation', sa.String(length=150), nullable=True),
    sa.Column('number_open_fireplaces', sa.String(length=150), nullable=True),
    sa.Column('double_glazing', sa.String(length=150), nullable=True),
    sa.Column('num_occupants', sa.Integer(), nullable=True),
    sa.Column('annual_gas_kwh', sa.Float(), nullable=True),
    sa.Column('annual_gas_estimated', sa.Boolean(), nullable=True),
    sa.Column('annual_gas_start_date', sa.Date(), nullable=True),
    sa.Column('annual_gas_end_date', sa.Date(), nullable=True),
    sa.Column('annual_elec_kwh', sa.Float(), nullable=True),
    sa.Column('annual_elec_estimated', sa.Boolean(), nullable=True),
    sa.Column('annual_elec_start_date', sa.Date(), nullable=True),
    sa.Column('annual_elec_end_date', sa.Date(), nullable=True),
    sa.Column('annual_solid_spend', sa.Float(), nullable=True),
    sa.Column('renewable_contribution_kwh', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_type_id'], ['building_types.id'], ),
    sa.ForeignKeyConstraint(['cooking_type_id'], ['cooking_types.id'], ),
    sa.ForeignKeyConstraint(['occupation_type_id'], ['occupation_types.id'], ),
    sa.ForeignKeyConstraint(['primary_heating_type_id'], ['space_heating_types.id'], ),
    sa.ForeignKeyConstraint(['secondary_heating_type_id'], ['space_heating_types.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.ForeignKeyConstraint(['wall_construction_type_id'], ['wall_construction_types.id'], ),
    sa.ForeignKeyConstraint(['water_heating_type_id'], ['water_heating_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pre_survey_details')
    op.drop_table('post_survey_details')
    # ### end Alembic commands ###
