"""empty message

Revision ID: 1408626b611e
Revises: 4c22b34b44ec
Create Date: 2016-12-30 16:22:39.090477

"""

# revision identifiers, used by Alembic.
revision = '1408626b611e'
down_revision = '4c22b34b44ec'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('can_heat_comfortably', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'can_heat_comfortably')
    # ### end Alembic commands ###
