"""empty message

Revision ID: 178beb0ef371
Revises: a8fa760ce67d
Create Date: 2017-03-03 17:47:58.174023

"""

# revision identifiers, used by Alembic.
revision = '178beb0ef371'
down_revision = 'a8fa760ce67d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thermal_image', sa.Column('building_type', sa.Enum('Flat', 'Maisonette', 'Mid terrace', 'End terrace', 'Semi-detatched', 'Detatched', 'Other'), nullable=True))
    op.add_column('thermal_image', sa.Column('keywords', sa.String(length=150), nullable=True))
    op.add_column('thermal_image', sa.Column('year_of_construction', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thermal_image', 'year_of_construction')
    op.drop_column('thermal_image', 'keywords')
    op.drop_column('thermal_image', 'building_type')
    # ### end Alembic commands ###
