"""empty message

Revision ID: 2befa872f592
Revises: be67351037ca
Create Date: 2018-10-17 09:02:10.760798

"""

# revision identifiers, used by Alembic.
revision = '2befa872f592'
down_revision = 'be67351037ca'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_lead_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'surveys', sa.Column('building_type_id', sa.Integer(), nullable=True))
    op.add_column(u'surveys', sa.Column('lead_status_id', sa.Integer(), nullable=True))
    op.add_column(u'surveys', sa.Column('ward_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'surveys', 'wards', ['ward_id'], ['id'])
    op.create_foreign_key(None, 'surveys', 'survey_lead_statuses', ['lead_status_id'], ['id'])
    op.create_foreign_key(None, 'surveys', 'building_types', ['building_type_id'], ['id'])
    op.drop_column(u'surveys', 'ward')
    op.drop_column(u'surveys', 'lead_status')
    op.drop_column(u'surveys', 'building_type')
    op.add_column(u'thermal_image', sa.Column('building_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'thermal_image', 'building_types', ['building_type_id'], ['id'])
    op.drop_column(u'thermal_image', 'building_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'thermal_image', sa.Column('building_type', mysql.ENUM(u'Flat', u'Maisonette', u'Mid terrace', u'End terrace', u'Semi-detatched', u'Detatched', u'Other'), nullable=True))
    op.drop_constraint(None, 'thermal_image', type_='foreignkey')
    op.drop_column(u'thermal_image', 'building_type_id')
    op.add_column(u'surveys', sa.Column('building_type', mysql.ENUM(u'Flat', u'Maisonette', u'Mid terrace', u'End terrace', u'Semi-detatched', u'Detatched', u'Other'), nullable=True))
    op.add_column(u'surveys', sa.Column('lead_status', mysql.ENUM(u'Possible', u'Successful', u'Dead'), nullable=True))
    op.add_column(u'surveys', sa.Column('ward', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_column(u'surveys', 'ward_id')
    op.drop_column(u'surveys', 'lead_status_id')
    op.drop_column(u'surveys', 'building_type_id')
    op.drop_table('survey_lead_statuses')
    # ### end Alembic commands ###
