"""empty message

Revision ID: 2ec175122d3d
Revises: c21cc634f43b
Create Date: 2016-12-15 09:33:08.668337

"""

# revision identifiers, used by Alembic.
revision = '2ec175122d3d'
down_revision = 'c21cc634f43b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('date_settled', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('paid_by', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('settled', sa.Boolean(), nullable=True))
    op.drop_index('number', table_name='invoices')
    op.drop_column('invoices', 'date_paid')
    op.drop_column('invoices', 'number')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('date_paid', sa.DATE(), nullable=True))
    op.create_index('number', 'invoices', ['number'], unique=True)
    op.drop_column('invoices', 'settled')
    op.drop_column('invoices', 'paid_by')
    op.drop_column('invoices', 'date_settled')
    ### end Alembic commands ###
