"""empty message

Revision ID: 324416c191fa
Revises: 394648ef62f8
Create Date: 2017-02-20 16:04:38.126386

"""

# revision identifiers, used by Alembic.
revision = '324416c191fa'
down_revision = '394648ef62f8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('followed_up', sa.Boolean(), nullable=True))
    op.add_column('surveys', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'notes')
    op.drop_column('surveys', 'followed_up')
    # ### end Alembic commands ###
