"""empty message

Revision ID: 32b1f65ae6a0
Revises: 6eb9c2bbd903
Create Date: 2017-02-11 19:03:20.994260

"""

# revision identifiers, used by Alembic.
revision = '32b1f65ae6a0'
down_revision = '6eb9c2bbd903'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'inventory_ibfk_2', 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'invoice_id')
    op.drop_constraint(u'kits_ibfk_1', 'kits', type_='foreignkey')
    op.drop_column('kits', 'invoice_id')
    op.drop_table('invoices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kits', sa.Column('invoice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'kits_ibfk_1', 'kits', 'invoices', ['invoice_id'], ['id'])
    op.add_column('inventory', sa.Column('invoice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'inventory_ibfk_2', 'inventory', 'invoices', ['invoice_id'], ['id'])
    op.create_table('invoices',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('reference', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('date_raised', sa.DATE(), nullable=True),
    sa.Column('category', mysql.ENUM(u'Salaries', u'NIC', u'Pension', u'Fees', u'License fees', u'Technical fees', u'Office', u'Legal/insurance', u'Publicity/printing', u'Training/video', u'Travel', u'Segments', u'Capital kit', u'Consumables', u'BEN/BCG', u'BEN/CEF', u'BCR/FoE', u'EEG', u'ALW'), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('date_settled', sa.DATE(), nullable=True),
    sa.Column('paid_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('settled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
