"""empty message

Revision ID: 394648ef62f8
Revises: 3efbb5e3cc73
Create Date: 2017-02-17 20:15:10.132483

"""

# revision identifiers, used by Alembic.
revision = '394648ef62f8'
down_revision = '3efbb5e3cc73'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('year_feedback', sa.Column('wellbeing_improvement', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('year_feedback', 'wellbeing_improvement')
    # ### end Alembic commands ###
