"""empty message

Revision ID: 4b6bafd37208
Revises: None
Create Date: 2016-11-22 19:30:42.865469

"""

# revision identifiers, used by Alembic.
revision = '4b6bafd37208'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('results')
    op.drop_table('users')
    op.add_column('inventory', sa.Column('credit_amount', sa.Float(), nullable=True))
    op.add_column('inventory', sa.Column('credit_date', sa.Date(), nullable=True))
    op.add_column('inventory', sa.Column('icloud_password', sa.String(length=25), nullable=True))
    op.add_column('inventory', sa.Column('icloud_username', sa.String(length=25), nullable=True))
    op.add_column('inventory', sa.Column('imei', sa.String(length=25), nullable=True))
    op.add_column('inventory', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('kit_id', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('loan_id', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('inventory', sa.Column('serial_number', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('sim_iccid', sa.String(length=25), nullable=True))
    op.add_column('inventory', sa.Column('value', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'inventory', 'loans', ['loan_id'], ['id'])
    op.create_foreign_key(None, 'inventory', 'invoices', ['invoice_id'], ['id'])
    op.create_foreign_key(None, 'inventory', 'kits', ['kit_id'], ['id'])
    op.drop_constraint(u'loans_ibfk_1', 'loans', type_='foreignkey')
    op.drop_column('loans', 'inventory_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('inventory_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'loans_ibfk_1', 'loans', 'inventory', ['inventory_id'], ['id'])
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'value')
    op.drop_column('inventory', 'sim_iccid')
    op.drop_column('inventory', 'serial_number')
    op.drop_column('inventory', 'phone_number')
    op.drop_column('inventory', 'loan_id')
    op.drop_column('inventory', 'kit_id')
    op.drop_column('inventory', 'invoice_id')
    op.drop_column('inventory', 'imei')
    op.drop_column('inventory', 'icloud_username')
    op.drop_column('inventory', 'icloud_password')
    op.drop_column('inventory', 'credit_date')
    op.drop_column('inventory', 'credit_amount')
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('results',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('kits')
    ### end Alembic commands ###
