"""empty message

Revision ID: 4c22b34b44ec
Revises: d483b95d0b07
Create Date: 2016-12-28 12:39:55.190394

"""

# revision identifiers, used by Alembic.
revision = '4c22b34b44ec'
down_revision = 'd483b95d0b07'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follow_ups', 'collected_cheese_box',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('invoices', 'settled',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('results', 'depth_loft_insulation',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('results', 'double_glazing',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('results', 'loaned_cheese_box',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('results', 'number_open_fireplaces',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('results', 'primary_heating_type',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('results', 'secondary_heating_type',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('surveys', 'fee_paid',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('surveys', 'free_survey_consideration',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('surveys', 'survey_complete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveys', 'survey_complete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('surveys', 'free_survey_consideration',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('surveys', 'fee_paid',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('results', 'secondary_heating_type',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('results', 'primary_heating_type',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('results', 'number_open_fireplaces',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('results', 'loaned_cheese_box',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('results', 'double_glazing',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('results', 'depth_loft_insulation',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('invoices', 'settled',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('follow_ups', 'collected_cheese_box',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
