"""empty message

Revision ID: 5570bf4dcce7
Revises: 5f7411c00819
Create Date: 2018-03-25 16:15:26.834049

"""

# revision identifiers, used by Alembic.
revision = '5570bf4dcce7'
down_revision = '5f7411c00819'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('year_feedback', sa.Column('behaviour_space', sa.Text(), nullable=True))
    op.add_column('year_feedback', sa.Column('behaviour_temperature', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('year_feedback', 'behaviour_temperature')
    op.drop_column('year_feedback', 'behaviour_space')
    # ### end Alembic commands ###
