"""empty message

Revision ID: 576c8ff566c5
Revises: 4a3875909698
Create Date: 2017-05-21 11:11:34.766432

"""

# revision identifiers, used by Alembic.
revision = '576c8ff566c5'
down_revision = '4a3875909698'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('people', 'first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('people', 'last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('people', 'password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('results', 'loaned_cheese_box',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('surveys', sa.Column('box_collected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveys', 'survey_complete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('surveys', 'free_survey_consideration',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('surveys', 'followed_up',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('surveys', 'fee_paid',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('surveys', 'can_heat_comfortably',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('surveys', 'box_collected')
    # ### end Alembic commands ###
