"""empty message

Revision ID: 58f308cbad50
Revises: 75c7e23626a0
Create Date: 2016-12-19 09:45:05.009567

"""

# revision identifiers, used by Alembic.
revision = '58f308cbad50'
down_revision = '75c7e23626a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('building_type', sa.Enum('Flat', 'Maisonette', 'Mid terrace', 'End terrace', 'Semi-detatched', 'Detatched', 'Other'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'building_type')
    # ### end Alembic commands ###
