"""empty message

Revision ID: 5c16728c9b8a
Revises: cdcf2498ef66
Create Date: 2016-12-03 14:38:45.231318

"""

# revision identifiers, used by Alembic.
revision = '5c16728c9b8a'
down_revision = 'cdcf2498ef66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'inventory', ['phone_number'])
    op.create_unique_constraint(None, 'inventory', ['sim_iccid'])
    op.create_unique_constraint(None, 'inventory', ['imei'])
    op.create_unique_constraint(None, 'inventory', ['serial_number'])
    op.create_unique_constraint(None, 'inventory', ['asset_number'])
    op.add_column('surveys', sa.Column('survey_request_date', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'survey_request_date')
    op.drop_constraint(None, 'inventory', type_='unique')
    op.drop_constraint(None, 'inventory', type_='unique')
    op.drop_constraint(None, 'inventory', type_='unique')
    op.drop_constraint(None, 'inventory', type_='unique')
    op.drop_constraint(None, 'inventory', type_='unique')
    ### end Alembic commands ###
