"""empty message

Revision ID: 5f7411c00819
Revises: 944a26b26735
Create Date: 2018-02-07 11:09:13.313599

"""

# revision identifiers, used by Alembic.
revision = '5f7411c00819'
down_revision = '944a26b26735'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cooking_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('occupation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('space_heating_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wall_construction_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('water_heating_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'results', sa.Column('building_type_id', sa.Integer(), nullable=True))
    op.add_column(u'results', sa.Column('cooking_type_id', sa.Integer(), nullable=True))
    op.add_column(u'results', sa.Column('occupation_type_id', sa.Integer(), nullable=True))
    op.add_column(u'results', sa.Column('primary_heating_type_id', sa.Integer(), nullable=True))
    op.add_column(u'results', sa.Column('secondary_heating_type_id', sa.Integer(), nullable=True))
    op.add_column(u'results', sa.Column('wall_construction_type_id', sa.Integer(), nullable=True))
    op.add_column(u'results', sa.Column('water_heating_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'results', 'cooking_types', ['cooking_type_id'], ['id'])
    op.create_foreign_key(None, 'results', 'wall_construction_types', ['wall_construction_type_id'], ['id'])
    op.create_foreign_key(None, 'results', 'space_heating_types', ['secondary_heating_type_id'], ['id'])
    op.create_foreign_key(None, 'results', 'space_heating_types', ['primary_heating_type_id'], ['id'])
    op.create_foreign_key(None, 'results', 'water_heating_types', ['water_heating_type_id'], ['id'])
    op.create_foreign_key(None, 'results', 'occupation_types', ['occupation_type_id'], ['id'])
    op.create_foreign_key(None, 'results', 'building_types', ['building_type_id'], ['id'])
    op.drop_column(u'results', 'wall_construction')
    op.drop_column(u'results', 'secondary_heating_type')
    op.drop_column(u'results', 'primary_heating_type')
    op.drop_column(u'results', 'building_type')
    op.drop_column(u'results', 'occupation_type')
    op.drop_column(u'results', 'water_heating_type')
    op.drop_column(u'results', 'cooking_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'results', sa.Column('cooking_type', mysql.ENUM(u'Unknown', u'Gas', u'Electricity', u'Other'), nullable=True))
    op.add_column(u'results', sa.Column('water_heating_type', mysql.ENUM(u'Unknown', u'Gas', u'Electricity', u'Solar', u'Shared/municipal', u'Heat pump', u'Other'), nullable=True))
    op.add_column(u'results', sa.Column('occupation_type', mysql.ENUM(u'Owned', u'Rented privately', u'Rented council', u'Rented housing association', u'Other'), nullable=True))
    op.add_column(u'results', sa.Column('building_type', mysql.ENUM(u'Flat', u'Maisonette', u'Mid terrace', u'End terrace', u'Semi-detatched', u'Detatched', u'Other'), nullable=True))
    op.add_column(u'results', sa.Column('primary_heating_type', mysql.VARCHAR(length=150), nullable=True))
    op.add_column(u'results', sa.Column('secondary_heating_type', mysql.VARCHAR(length=150), nullable=True))
    op.add_column(u'results', sa.Column('wall_construction', mysql.ENUM(u'Solid brick', u'Insulated cavity', u'Uninsulated cavity', u'Stone', u'Timber', u'Other'), nullable=True))
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_column(u'results', 'water_heating_type_id')
    op.drop_column(u'results', 'wall_construction_type_id')
    op.drop_column(u'results', 'secondary_heating_type_id')
    op.drop_column(u'results', 'primary_heating_type_id')
    op.drop_column(u'results', 'occupation_type_id')
    op.drop_column(u'results', 'cooking_type_id')
    op.drop_column(u'results', 'building_type_id')
    op.drop_table('water_heating_types')
    op.drop_table('wards')
    op.drop_table('wall_construction_types')
    op.drop_table('space_heating_types')
    op.drop_table('occupation_types')
    op.drop_table('cooking_types')
    op.drop_table('building_types')
    # ### end Alembic commands ###
