"""empty message

Revision ID: 665ce36ab2ad
Revises: 58f308cbad50
Create Date: 2016-12-21 11:07:57.589640

"""

# revision identifiers, used by Alembic.
revision = '665ce36ab2ad'
down_revision = '58f308cbad50'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_ups', sa.Column('collected_cheese_box', sa.Boolean(), nullable=True))
    op.add_column('results', sa.Column('double_glazing', sa.String(length=30), nullable=True))
    op.add_column('results', sa.Column('loaned_cheese_box', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'loaned_cheese_box')
    op.drop_column('results', 'double_glazing')
    op.drop_column('follow_ups', 'collected_cheese_box')
    # ### end Alembic commands ###
