"""empty message

Revision ID: 6eb9c2bbd903
Revises: 1408626b611e
Create Date: 2017-02-11 18:54:39.607447

"""

# revision identifiers, used by Alembic.
revision = '6eb9c2bbd903'
down_revision = '1408626b611e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('month_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('householders_name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('annual_gas_kwh', sa.Float(), nullable=True),
    sa.Column('annual_elec_kwh', sa.Float(), nullable=True),
    sa.Column('annual_solid_spend', sa.Float(), nullable=True),
    sa.Column('renewable_contrib_kwh', sa.Float(), nullable=True),
    sa.Column('planned_actions', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('year_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('householders_name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('annual_gas_kwh', sa.Float(), nullable=True),
    sa.Column('annual_elec_kwh', sa.Float(), nullable=True),
    sa.Column('annual_solid_spend', sa.Float(), nullable=True),
    sa.Column('renewable_contrib_kwh', sa.Float(), nullable=True),
    sa.Column('diy_work', sa.Text(), nullable=True),
    sa.Column('prof_work', sa.Text(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('planned_work', sa.Text(), nullable=True),
    sa.Column('behaviour_changes', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('follow_ups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_ups',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('type', mysql.ENUM(u'One month', u'One year'), nullable=True),
    sa.Column('householders_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('address_line', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('annual_gas_kwh', mysql.FLOAT(), nullable=True),
    sa.Column('annual_elec_kwh', mysql.FLOAT(), nullable=True),
    sa.Column('annual_solid_spend', mysql.FLOAT(), nullable=True),
    sa.Column('renewable_contribution_kwh', mysql.FLOAT(), nullable=True),
    sa.Column('householder_actions', mysql.TEXT(), nullable=True),
    sa.Column('householder_feedback', mysql.TEXT(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('survey_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('collected_cheese_box', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], [u'surveys.id'], name=u'follow_ups_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('year_feedback')
    op.drop_table('month_feedback')
    # ### end Alembic commands ###
