"""empty message

Revision ID: 7105426f8629
Revises: 07a99d211173
Create Date: 2019-11-01 09:10:41.218329

"""

# revision identifiers, used by Alembic.
revision = '7105426f8629'
down_revision = '07a99d211173'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_survey_details', sa.Column('asbestos_details', sa.Text(), nullable=True))
    op.add_column('pre_survey_details', sa.Column('has_asbestos', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_survey_details', 'has_asbestos')
    op.drop_column('pre_survey_details', 'asbestos_details')
    # ### end Alembic commands ###
