"""empty message

Revision ID: 75c7e23626a0
Revises: 2ec175122d3d
Create Date: 2016-12-19 09:35:14.382567

"""

# revision identifiers, used by Alembic.
revision = '75c7e23626a0'
down_revision = '2ec175122d3d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('One month', 'One year'), nullable=True),
    sa.Column('householders_name', sa.String(length=50), nullable=True),
    sa.Column('address_line', sa.String(length=100), nullable=True),
    sa.Column('annual_gas_kwh', sa.Float(), nullable=True),
    sa.Column('annual_elec_kwh', sa.Float(), nullable=True),
    sa.Column('annual_solid_spend', sa.Float(), nullable=True),
    sa.Column('renewable_contribution_kwh', sa.Float(), nullable=True),
    sa.Column('householder_actions', sa.Text(), nullable=True),
    sa.Column('householder_feedback', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surveyors_name', sa.String(length=50), nullable=True),
    sa.Column('householders_name', sa.String(length=50), nullable=True),
    sa.Column('address_line', sa.String(length=100), nullable=True),
    sa.Column('survey_date', sa.Date(), nullable=True),
    sa.Column('external_temperature', sa.Float(), nullable=True),
    sa.Column('cheese_box_number', sa.String(length=25), nullable=True),
    sa.Column('building_type', sa.Enum('Flat', 'Maisonette', 'Mid terrace', 'End terrace', 'Semi-detatched', 'Detatched', 'Other'), nullable=True),
    sa.Column('year_of_construction', sa.Integer(), nullable=True),
    sa.Column('wall_construction', sa.Enum('Solid brick', 'Insulated cavity', 'Uninsulated cavity', 'Stone', 'Timber', 'Other'), nullable=True),
    sa.Column('occupation_type', sa.Enum('Owned', 'Rented privately', 'Rented council', 'Rented housing association', 'Other'), nullable=True),
    sa.Column('primary_heating_type', sa.String(length=30), nullable=True),
    sa.Column('secondary_heating_type', sa.String(length=30), nullable=True),
    sa.Column('depth_loft_insulation', sa.String(length=30), nullable=True),
    sa.Column('number_open_fireplaces', sa.String(length=30), nullable=True),
    sa.Column('num_occupants', sa.Integer(), nullable=True),
    sa.Column('annual_gas_kwh', sa.Float(), nullable=True),
    sa.Column('annual_elec_kwh', sa.Float(), nullable=True),
    sa.Column('annual_solid_spend', sa.Float(), nullable=True),
    sa.Column('renewable_contribution_kwh', sa.Float(), nullable=True),
    sa.Column('faults_identified', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'surveys', 'renewable_contribution_post')
    op.drop_column(u'surveys', 'solid_annual_post')
    op.drop_column(u'surveys', 'follow_up_1_complete')
    op.drop_column(u'surveys', 'remedial_measures')
    op.drop_column(u'surveys', 'elec_annual_post')
    op.drop_column(u'surveys', 'elec_annual_pre')
    op.drop_column(u'surveys', 'follow_up_3_complete')
    op.drop_column(u'surveys', 'gas_annual_post')
    op.drop_column(u'surveys', 'building_construction')
    op.drop_column(u'surveys', 'surveyor_comments')
    op.drop_column(u'surveys', 'follow_up_2_complete')
    op.drop_column(u'surveys', 'gas_annual_pre')
    op.drop_column(u'surveys', 'householder_comments')
    op.drop_column(u'surveys', 'building_age')
    op.drop_column(u'surveys', 'building_construction_other')
    op.drop_column(u'surveys', 'follow_up_2_date')
    op.drop_column(u'surveys', 'faults_identified')
    op.drop_column(u'surveys', 'solid_annual_pre')
    op.drop_column(u'surveys', 'follow_up_1_date')
    op.drop_column(u'surveys', 'follow_up_3_date')
    op.drop_column(u'surveys', 'renewable_contribution_pre')
    op.drop_column(u'surveys', 'householder_actions')
    op.drop_column(u'surveys', 'num_occupants')
    op.drop_column(u'surveys', 'building_type_other')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'surveys', sa.Column('building_type_other', mysql.VARCHAR(length=100), nullable=True))
    op.add_column(u'surveys', sa.Column('num_occupants', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'surveys', sa.Column('householder_actions', mysql.TEXT(), nullable=True))
    op.add_column(u'surveys', sa.Column('renewable_contribution_pre', mysql.FLOAT(), nullable=True))
    op.add_column(u'surveys', sa.Column('follow_up_3_date', sa.DATE(), nullable=True))
    op.add_column(u'surveys', sa.Column('follow_up_1_date', sa.DATE(), nullable=True))
    op.add_column(u'surveys', sa.Column('solid_annual_pre', mysql.FLOAT(), nullable=True))
    op.add_column(u'surveys', sa.Column('faults_identified', mysql.TEXT(), nullable=True))
    op.add_column(u'surveys', sa.Column('follow_up_2_date', sa.DATE(), nullable=True))
    op.add_column(u'surveys', sa.Column('building_construction_other', mysql.VARCHAR(length=100), nullable=True))
    op.add_column(u'surveys', sa.Column('building_age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'surveys', sa.Column('householder_comments', mysql.TEXT(), nullable=True))
    op.add_column(u'surveys', sa.Column('gas_annual_pre', mysql.FLOAT(), nullable=True))
    op.add_column(u'surveys', sa.Column('follow_up_2_complete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column(u'surveys', sa.Column('surveyor_comments', mysql.TEXT(), nullable=True))
    op.add_column(u'surveys', sa.Column('building_construction', mysql.VARCHAR(length=25), nullable=True))
    op.add_column(u'surveys', sa.Column('gas_annual_post', mysql.FLOAT(), nullable=True))
    op.add_column(u'surveys', sa.Column('follow_up_3_complete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column(u'surveys', sa.Column('elec_annual_pre', mysql.FLOAT(), nullable=True))
    op.add_column(u'surveys', sa.Column('elec_annual_post', mysql.FLOAT(), nullable=True))
    op.add_column(u'surveys', sa.Column('remedial_measures', mysql.TEXT(), nullable=True))
    op.add_column(u'surveys', sa.Column('follow_up_1_complete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column(u'surveys', sa.Column('solid_annual_post', mysql.FLOAT(), nullable=True))
    op.add_column(u'surveys', sa.Column('renewable_contribution_post', mysql.FLOAT(), nullable=True))
    op.drop_table('results')
    op.drop_table('follow_ups')
    # ### end Alembic commands ###
