"""empty message

Revision ID: 7af0b7decdf3
Revises: 576c8ff566c5
Create Date: 2017-06-05 12:30:37.594344

"""

# revision identifiers, used by Alembic.
revision = '7af0b7decdf3'
down_revision = '576c8ff566c5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveys', 'referral',
               existing_type=mysql.VARCHAR(length=100),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveys', 'referral',
               existing_type=mysql.VARCHAR(length=250),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
