"""empty message

Revision ID: 91a0734d287e
Revises: d98b6ece0998
Create Date: 2017-11-23 13:45:20.514524

"""

# revision identifiers, used by Alembic.
revision = '91a0734d287e'
down_revision = 'd98b6ece0998'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('mobile', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'mobile')
    # ### end Alembic commands ###
