"""empty message

Revision ID: 9306332651d2
Revises: 7105426f8629
Create Date: 2020-02-08 15:26:48.826565

"""

# revision identifiers, used by Alembic.
revision = '9306332651d2'
down_revision = '7105426f8629'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('asbestos_details', sa.Text(), nullable=True))
    op.add_column('surveys', sa.Column('has_asbestos', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'has_asbestos')
    op.drop_column('surveys', 'asbestos_details')
    # ### end Alembic commands ###
