"""empty message

Revision ID: a96f386eea88
Revises: 324416c191fa
Create Date: 2017-02-25 17:20:43.479230

"""

# revision identifiers, used by Alembic.
revision = 'a96f386eea88'
down_revision = '324416c191fa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thermal_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Unicode(length=100), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('submitted_by', sa.Unicode(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thermal_image')
    # ### end Alembic commands ###
