"""empty message

Revision ID: ba4fab762f73
Revises: 5570bf4dcce7
Create Date: 2018-05-24 12:42:32.358893

"""

# revision identifiers, used by Alembic.
revision = 'ba4fab762f73'
down_revision = '5570bf4dcce7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('photo_release', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'photo_release')
    # ### end Alembic commands ###
