"""empty message

Revision ID: be67351037ca
Revises: d321d3e39f4d
Create Date: 2018-06-20 14:58:47.126693

"""

# revision identifiers, used by Alembic.
revision = 'be67351037ca'
down_revision = 'd321d3e39f4d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('representative_1_name', sa.String(length=100), nullable=True),
    sa.Column('representative_1_email', sa.String(length=100), nullable=True),
    sa.Column('representative_1_telephone', sa.String(length=100), nullable=True),
    sa.Column('representative_2_name', sa.String(length=100), nullable=True),
    sa.Column('representative_2_email', sa.String(length=100), nullable=True),
    sa.Column('representative_2_telephone', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    # ### end Alembic commands ###
