"""empty message

Revision ID: c21cc634f43b
Revises: e39471735752
Create Date: 2016-12-11 18:06:48.044566

"""

# revision identifiers, used by Alembic.
revision = 'c21cc634f43b'
down_revision = 'e39471735752'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('fee_paid', sa.Boolean(), nullable=True))
    op.add_column('surveys', sa.Column('fee_paid_date', sa.Date(), nullable=True))
    op.drop_column('surveys', 'agree_to_requirements')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('agree_to_requirements', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('surveys', 'fee_paid_date')
    op.drop_column('surveys', 'fee_paid')
    ### end Alembic commands ###
