"""empty message

Revision ID: cdcf2498ef66
Revises: 4b6bafd37208
Create Date: 2016-11-28 21:22:59.577215

"""

# revision identifiers, used by Alembic.
revision = 'cdcf2498ef66'
down_revision = '4b6bafd37208'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('date_of_purchase', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'date_of_purchase')
    ### end Alembic commands ###
