"""empty message

Revision ID: d321d3e39f4d
Revises: ba4fab762f73
Create Date: 2018-06-20 09:03:02.734237

"""

# revision identifiers, used by Alembic.
revision = 'd321d3e39f4d'
down_revision = 'ba4fab762f73'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('phase', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'phase')
    # ### end Alembic commands ###
