"""empty message

Revision ID: d483b95d0b07
Revises: 665ce36ab2ad
Create Date: 2016-12-27 11:29:04.132975

"""

# revision identifiers, used by Alembic.
revision = 'd483b95d0b07'
down_revision = '665ce36ab2ad'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'inventory_ibfk_1', 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'loan_id')
    op.drop_constraint(u'kits_ibfk_2', 'kits', type_='foreignkey')
    op.drop_column('kits', 'loan_id')
    op.drop_table('loans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kits', sa.Column('loan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'kits_ibfk_2', 'kits', 'loans', ['loan_id'], ['id'])
    op.add_column('inventory', sa.Column('loan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'inventory_ibfk_1', 'inventory', 'loans', ['loan_id'], ['id'])
    op.create_table('loans',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('telephone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
