"""empty message

Revision ID: d5379fca1674
Revises: 2befa872f592
Create Date: 2019-01-17 07:56:21.018076

"""

# revision identifiers, used by Alembic.
revision = 'd5379fca1674'
down_revision = '2befa872f592'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('month_feedback', sa.Column('any_completed_actions', sa.Boolean(), nullable=True))
    op.add_column('month_feedback', sa.Column('any_wellbeing_improvement', sa.Boolean(), nullable=True))
    op.add_column('month_feedback', sa.Column('behaviour_changes', sa.Text(), nullable=True))
    op.add_column('month_feedback', sa.Column('behaviour_space', sa.Text(), nullable=True))
    op.add_column('month_feedback', sa.Column('behaviour_temperature', sa.Text(), nullable=True))
    op.add_column('month_feedback', sa.Column('wellbeing_improvement', sa.Text(), nullable=True))
    op.add_column('surveys', sa.Column('special_considerations', sa.Text(), nullable=True))
    op.add_column('year_feedback', sa.Column('any_completed_actions', sa.Boolean(), nullable=True))
    op.add_column('year_feedback', sa.Column('any_wellbeing_improvement', sa.Boolean(), nullable=True))
    op.add_column('year_feedback', sa.Column('non_homeowner_work', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('year_feedback', 'non_homeowner_work')
    op.drop_column('year_feedback', 'any_wellbeing_improvement')
    op.drop_column('year_feedback', 'any_completed_actions')
    op.drop_column('surveys', 'special_considerations')
    op.drop_column('month_feedback', 'wellbeing_improvement')
    op.drop_column('month_feedback', 'behaviour_temperature')
    op.drop_column('month_feedback', 'behaviour_space')
    op.drop_column('month_feedback', 'behaviour_changes')
    op.drop_column('month_feedback', 'any_wellbeing_improvement')
    op.drop_column('month_feedback', 'any_completed_actions')
    # ### end Alembic commands ###
