"""empty message

Revision ID: d98b6ece0998
Revises: ad1f138b9493
Create Date: 2017-10-25 10:54:52.283604

"""

# revision identifiers, used by Alembic.
revision = 'd98b6ece0998'
down_revision = 'ad1f138b9493'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('assistant_surveyor', sa.String(length=50), nullable=True))
    op.alter_column('results', 'surveyors_name', existing_type=sa.String(length=50), new_column_name='lead_surveyor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('results', 'lead_surveyor', existing_type=sa.String(length=50), new_column_name='surveyors_name')
    op.drop_column('results', 'assistant_surveyor')
    # ### end Alembic commands ###
