"""empty message

Revision ID: e4a48be2ca4e
Revises: 769ded4a3cd3
Create Date: 2018-01-15 09:23:37.404389

"""

# revision identifiers, used by Alembic.
revision = 'e4a48be2ca4e'
down_revision = '769ded4a3cd3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('month_feedback', sa.Column('annual_elec_end_date', sa.Date(), nullable=True))
    op.add_column('month_feedback', sa.Column('annual_elec_estimated', sa.Boolean(), nullable=True))
    op.add_column('month_feedback', sa.Column('annual_elec_start_date', sa.Date(), nullable=True))
    op.add_column('month_feedback', sa.Column('annual_gas_end_date', sa.Date(), nullable=True))
    op.add_column('month_feedback', sa.Column('annual_gas_estimated', sa.Boolean(), nullable=True))
    op.add_column('month_feedback', sa.Column('annual_gas_start_date', sa.Date(), nullable=True))
    op.add_column('month_feedback', sa.Column('cheese_box_1to5', sa.Integer(), nullable=True))
    op.add_column('month_feedback', sa.Column('recommend_1to5', sa.Integer(), nullable=True))
    op.add_column('month_feedback', sa.Column('satisfaction_1to5', sa.Integer(), nullable=True))
    op.add_column('month_feedback', sa.Column('survey_value_1to5', sa.Integer(), nullable=True))
    op.add_column('month_feedback', sa.Column('survey_video_1to5', sa.Integer(), nullable=True))
    op.add_column('month_feedback', sa.Column('surveyor_conduct_1to5', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('annual_elec_end_date', sa.Date(), nullable=True))
    op.add_column('results', sa.Column('annual_elec_estimated', sa.Boolean(), nullable=True))
    op.add_column('results', sa.Column('annual_elec_start_date', sa.Date(), nullable=True))
    op.add_column('results', sa.Column('annual_gas_end_date', sa.Date(), nullable=True))
    op.add_column('results', sa.Column('annual_gas_estimated', sa.Boolean(), nullable=True))
    op.add_column('results', sa.Column('annual_gas_start_date', sa.Date(), nullable=True))
    op.add_column('results', sa.Column('cooking_type', sa.Enum('Unknown', 'Gas', 'Electricity', 'Other'), nullable=True))
    op.add_column('results', sa.Column('water_heating_type', sa.Enum('Unknown', 'Gas', 'Electricity', 'Solar', 'Shared/municipal', 'Geothermal', 'Other'), nullable=True))
    op.add_column('year_feedback', sa.Column('annual_elec_end_date', sa.Date(), nullable=True))
    op.add_column('year_feedback', sa.Column('annual_elec_estimated', sa.Boolean(), nullable=True))
    op.add_column('year_feedback', sa.Column('annual_elec_start_date', sa.Date(), nullable=True))
    op.add_column('year_feedback', sa.Column('annual_gas_end_date', sa.Date(), nullable=True))
    op.add_column('year_feedback', sa.Column('annual_gas_estimated', sa.Boolean(), nullable=True))
    op.add_column('year_feedback', sa.Column('annual_gas_start_date', sa.Date(), nullable=True))
    op.add_column('year_feedback', sa.Column('total_spent_diy', sa.Float(), nullable=True))
    op.add_column('year_feedback', sa.Column('total_spent_local', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('year_feedback', 'total_spent_local')
    op.drop_column('year_feedback', 'total_spent_diy')
    op.drop_column('year_feedback', 'annual_gas_start_date')
    op.drop_column('year_feedback', 'annual_gas_estimated')
    op.drop_column('year_feedback', 'annual_gas_end_date')
    op.drop_column('year_feedback', 'annual_elec_start_date')
    op.drop_column('year_feedback', 'annual_elec_estimated')
    op.drop_column('year_feedback', 'annual_elec_end_date')
    op.drop_column('results', 'water_heating_type')
    op.drop_column('results', 'cooking_type')
    op.drop_column('results', 'annual_gas_start_date')
    op.drop_column('results', 'annual_gas_estimated')
    op.drop_column('results', 'annual_gas_end_date')
    op.drop_column('results', 'annual_elec_start_date')
    op.drop_column('results', 'annual_elec_estimated')
    op.drop_column('results', 'annual_elec_end_date')
    op.drop_column('month_feedback', 'surveyor_conduct_1to5')
    op.drop_column('month_feedback', 'survey_video_1to5')
    op.drop_column('month_feedback', 'survey_value_1to5')
    op.drop_column('month_feedback', 'satisfaction_1to5')
    op.drop_column('month_feedback', 'recommend_1to5')
    op.drop_column('month_feedback', 'cheese_box_1to5')
    op.drop_column('month_feedback', 'annual_gas_start_date')
    op.drop_column('month_feedback', 'annual_gas_estimated')
    op.drop_column('month_feedback', 'annual_gas_end_date')
    op.drop_column('month_feedback', 'annual_elec_start_date')
    op.drop_column('month_feedback', 'annual_elec_estimated')
    op.drop_column('month_feedback', 'annual_elec_end_date')
    # ### end Alembic commands ###
