"""empty message

Revision ID: eb73548fec3b
Revises: d5379fca1674
Create Date: 2019-01-17 17:35:14.399503

"""

# revision identifiers, used by Alembic.
revision = 'eb73548fec3b'
down_revision = 'd5379fca1674'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('month_feedback', sa.Column('any_behaviour_change', sa.Boolean(), nullable=True))
    op.add_column('month_feedback', sa.Column('any_planned_work', sa.Boolean(), nullable=True))
    op.add_column('year_feedback', sa.Column('any_behaviour_change', sa.Boolean(), nullable=True))
    op.add_column('year_feedback', sa.Column('any_planned_work', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('year_feedback', 'any_planned_work')
    op.drop_column('year_feedback', 'any_behaviour_change')
    op.drop_column('month_feedback', 'any_planned_work')
    op.drop_column('month_feedback', 'any_behaviour_change')
    # ### end Alembic commands ###
