"""empty message

Revision ID: f2114004dfcd
Revises: 178beb0ef371
Create Date: 2017-04-23 11:26:37.479157

"""

# revision identifiers, used by Alembic.
revision = 'f2114004dfcd'
down_revision = '178beb0ef371'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('month_feedback', sa.Column('cheese_box', sa.Text(), nullable=True))
    op.add_column('month_feedback', sa.Column('collected_by', sa.String(length=50), nullable=True))
    op.add_column('month_feedback', sa.Column('completed_actions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('month_feedback', 'completed_actions')
    op.drop_column('month_feedback', 'collected_by')
    op.drop_column('month_feedback', 'cheese_box')
    # ### end Alembic commands ###
