"""empty message

Revision ID: f7cdd29c0d08
Revises: eb73548fec3b
Create Date: 2019-09-22 13:56:17.623696

"""

# revision identifiers, used by Alembic.
revision = 'f7cdd29c0d08'
down_revision = 'eb73548fec3b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('camera_kit_number', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'camera_kit_number')
    # ### end Alembic commands ###
